### ISSUE TITLE
Docker-in-Docker 19.03.6 hangs during execution

### ISSUE THREAD

**Issue by tmaczukin** [docker-library/docker#216] opened 2020-02-14 14:39 UTC
We've received several reports that jobs running in GitLab CI and using the Docker-in-Docker approach to build images started to hang during execution. Some examples can be found at:

- https://gitlab.com/gitlab-org/gitlab-runner/issues/6697
- https://gitlab.com/gitlab-com/support-forum/issues/5194

Please notice, that the problem is not on pulling the `gitlab/gitlab-runner-helper` image, which is done properly and is part of a `post build` step **after** the hanging job was terminated. The failure happens when a Docker image is being build, using the Docker-in-Docker service from `docker:dind` image.

Reviewing all of the cases we've found that they all are caused by using `docker:dind` or `doker:19.03-dind`, so the _floating_ versions pointing to `docker:19.03.6-dind` which was released several hours ago. The time of the image release aligns with all of the reports that we've received.

The only change in the image, since the last `docker:19.03.5-dind` push (which works!) was done, is the automatic update from Docker `19.03.5` to Docker `19.03.6` (https://github.com/docker-library/docker/commit/3dc42d46491d14b9b87f553bd46a45954ecec8ea). Whatever is causing the problems, it's in Docker itself.

Leaving this as a note and a workaround description for all of you who may look here to find out problems with GitLab CI and Docker-in-Docker, which was happening in the past :)

So, if you think you're affected by this issue, set the used image explicitly to `docker:19.03.5-dind`.

Also... maybe it's worth to revert the release of `docker:19.03.6-dind` until it's fixed?

**Comment by tmaczukin** [comment] 2020-02-14 14:40
fyi @tianon

**Comment by wglambert** [comment] 2020-02-14 17:45
Looks like there's some incompatibility with  [docker:19.03.6-dind](https://github.com/docker-library/official-images/pull/7469) and gitlab-runners

In the meantime using `19.03.5` should work
From [Tomasz Maczukin](https://gitlab.com/gitlab-com/support-forum/issues/5194#note_288435048); their documentation notes
`In the examples below, we are using Docker images tags to specify a specific version, such as docker:19.03.1. If tags like docker:stable are used, you have no control over what version is going to be used and this can lead to unpredictable behavior, especially when new versions are released.`

**Comment by tianon** [comment] 2020-02-14 22:31
Huh, this is definitely a weird one!  I wonder if we can figure out a smaller reproducer outside of GitLab so it's easier for us (and ultimately the upstream Docker maintainers) to dig into and figure out what's going wrong.  I tried just running `dind`, starting and stopping a container, and then stopping the daemon, but everything worked fine and nothing hung. :disappointed:

**Comment by tianon** [comment] 2020-02-14 22:36
In the meantime, if you've got an environment where the container is currently hung, getting `docker logs` and probably `docker top` off the `dind` container would probably be really useful.

**Comment by tao12345666333** [comment] 2020-02-15 04:40
Related issues: https://github.com/moby/moby/issues/40514

> We found the [issue in containerd 1.2.12](https://github.com/containerd/containerd/issues/4023) which seems to affect only some configurations of machines (likely related to single-core).
> 
> As a stopgap, we revoked containerd 1.2.12 packages while containerd does a 1.2.13 hotfix release.
> Fresh installs should work as expected.
> 
> For users who hit this issue (thus have `containerd --version` showing 1.2.12) you can fix it by running:
> 
> * on yum based distros: `yum remove -y containerd.io && yum clean all && yum makecache && yum install -y containerd.io`
> * on apt based distros: I couldn't figure out how to get rid of the apt cache in a way that installs containerd 1.2.10 instead of 1.2.12. It seems that apt-get clean is not enough. However, weirdly, I could get it to work by modifying the apt sources and running apt-get update. If you installed docker with the `curl -fsSL https://get.docker.com/ | sh` script I believe this worked for me: `service docker stop && service containerd stop && apt purge containerd.io docker-ce docker-ce-cli && rm -f /etc/apt/sources.list.d/docker.list && curl -fsSL https://get.docker.com/ | sh`
> 
> If you're using bundles from static binaries, for now please downgrade to 19.03.5.
> 
> Please let us know if this worked for you and I'll update instructions if needed. Sincere apologies!

**Comment by tmaczukin** [comment] 2020-02-15 11:40
That would fully explain why we've seen this on GitLab.com's Shared Runners (which use a single core VMs) but were unable to reproduce it locally on our personal machines!

**Comment by avwsolutions** [comment] 2020-02-17 11:07
Also here we experiencing issues with the 19.03.6  release with hanging pipelines in Gitlab (using :latest and :dind tag).

Now pinned the versions to  19.03.5, which solves hanging behaviour during our builds.

**Comment by collinmurray** [comment] 2020-02-17 11:44
Sorry to "me too" but I wanted to verify from someone else running GitLab Runners.

I can confirm we're seeing this issue on our pipelines too. We're running GitlabRunners on AWS and our pipelines are hanging on:
```
COPY . .

# Cleanup and get deps
RUN rm -Rf _build  //<- Hangs here.
```

Changing our docker image in our gitlabci.yaml file to
```
services:
  - docker:19.03.5-dind
```
resolved the issue and the build is working fine. 

Thanks for working on this issue, looking forward to a resolution.

**Comment by thaJeztah** [comment] 2020-02-17 22:32
The problem looks to be limited to single-core machines. A fix is in progress in containerd; https://github.com/containerd/containerd/pull/4025

**Comment by shinebayar-g** [comment] 2020-02-18 03:44
Having same issues on gitlab-ci runners as well. Noticed that 19.03.6 was released few days ago, reverted back to 19.03.5 fixed the issue. (We were just using `19.03` tag ..)

Thanks for the quick fix. :1st_place_medal:
```
...
WORKDIR /app/
RUN chown -R node:node /app    <= hangs there.
...
```

**Comment by inakimalerba** [comment] 2020-02-18 12:15
I can reproduce this issue interacting with any file (ls, echo, cat).

https://salsa.debian.org/ina-guest/test/pipelines/110144

**Comment by irufus** [comment] 2020-02-18 20:02
TIL do not rely on latest for anything!

**Comment by tmaczukin** [comment] 2020-11-18 13:23
As this problem was resolved months ago I think the issue can be closed.

Thanks for fixing this! :slightly_smiling_face:

**Closed** 2020-11-18 13:24 UTC
Labels: Issue
