### ISSUE TITLE
Add GNU Make to non-DinD images

### ISSUE THREAD

**Issue by lubo** [docker-library/docker#147] opened 2019-03-24 09:14 UTC
Could you add GNU Make to non-DinD images, please? It's a very lightweight package and I believe many people use it on their CI.

**Comment by tianon** [comment] 2019-03-29 23:43
I'm a bit confused -- what does GNU Make have to do with Docker-in-Docker?

I think this is conceptually a duplicate of https://github.com/docker-library/docker/issues/56 and https://github.com/docker-library/docker/issues/57 (which are asking for `openssl` and `curl` to be included, which were rejected for similar reasons to what I'd give here -- GNU Make, however popular, is not necessary nor even used by a stock Docker installation, so doesn't really make much sense for us to include, especially given how quickly and painlessly it installs via `apk add`).

**Comment by lubo** [comment] 2019-03-30 07:36
Yes, this is conceptually a duplicate of the mentioned issues and I agree with you. However, what's up with the `git` variant of this image? Does Docker require Git or was the variant added because of popularity/demand?

**Comment by tianon** [comment] 2019-03-30 14:22
Docker has built in functionality that invokes Git directly, but it's not
popular or well-known and Git is somewhat bulky so that optional
functionality got it's own tag instead.

**Closed** 2019-03-31 08:17 UTC
Labels: Request
