### ISSUE TITLE
IPTables Change, can't run Gitlab CI CD anymore

### ISSUE THREAD

**Issue by intsanerarity** [docker-library/docker#464] opened 2023-12-15 12:07 UTC
Hey,

with your newest Version i get this error from my CI/CD Pipeline 
"error during connect: Post "http://docker:2375/v1.24/auth": dial tcp: lookup docker on 169.254.169.254:53: no such host"

i set dind fix on 23.0.6 and everything is working fine - any suggestions?

best regards

steven

**Comment by manneorama** [comment] 2023-12-15 12:12
Same here but on Github using `action-runner-controller` in GKE with `docker:dind` as a sidecar. Worked around it by pinning `docker:dind` to the previous version in the runner controller Helm chart.

**Comment by stevexuereb** [comment] 2023-12-15 12:39
@manneorama  This is a duplicate of https://github.com/docker-library/docker/issues/463, for GitLab.com specifics you can check https://gitlab.com/gitlab-com/gl-infra/production/-/issues/17283

**Comment by tianon** [comment] 2023-12-15 17:57
Duplicate of https://github.com/docker-library/docker/issues/463 :+1: :heart:

**Closed by tianon** 2023-12-15 17:57 UTC
