### ISSUE TITLE
apt-get update in dind

### ISSUE THREAD

**Issue by Goram** [docker-library/docker#39] opened 2017-01-20 10:14 UTC
Hi,

Setup:
Win 10 Host - 1. Layer Docker Container (dind 1.13.0) - 2. Layer Docker Container (Debian:lastest)

I want to apt-get update in dind, everything works as expected in the 1. layer, but in the 2. I´ll get:
```
root@9d27879cab3f:/# apt-get update
Err http://security.debian.org jessie/updates InRelease
Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Err http://httpredir.debian.org jessie InRelease
Err http://httpredir.debian.org jessie-updates InRelease
Err http://httpredir.debian.org jessie Release.gpg
  Could not resolve 'httpredir.debian.org'
Err http://httpredir.debian.org jessie-updates Release.gpg
  Could not resolve 'httpredir.debian.org'
Reading package lists... Done
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/InRelease
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/InRelease
W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease
W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'httpredir.debian.org'
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'httpredir.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
I asked in the irc channel, but no resolution and was asked for /etc/resolv.conf:
1. Layer:
```
search xxx.company.local
nameserver 127.0.0.11
options ndots:0
```

2. Layer:
```
search xxx.company.local
options ndots:0

nameserver 8.8.8.8
nameserver 8.8.4.4
```

Any ideas?

**Comment by yosifkit** [comment] 2017-01-20 22:40
Let me see if I can replicate this.

- Windows 10 host
  - ["Docker for Windows"](https://docs.docker.com/docker-for-windows/) or [Docker Toolbox](https://www.docker.com/products/docker-toolbox) with boot2docker?
- any special config on the Windows Host?
  - the boot2docker VM?
- `docker version` and `docker info` on the host?

Did you run your containers something like this?

```console
$ # start a docker in docker container
$ docker run --privileged --name some-docker -d -p 6000:2375 docker:1.13-dind
$ # setup local docker to talk to it and run a debian container
$ # [ip-of-vm] would be the value of "docker-machine ip default"
$ # or "localhost" when using "docker for windows"
$ docker -H tcp://[ip-of-vm]:6000 run -it --rm debian:jessie
root@9d27879cab3f:/#  apt-get update
....
```

**Comment by duduu** [comment] 2017-03-02 14:51
Hi,

I suppose that your pc or laptop is behind a proxy like as usual in corporative offices.
This is what I did to to make it works.
What I saw is the docker proxy setting does not works inside your new virtual machine therefore you have to configure the proxy configuration inside of the virtual machine that you are building.
Inside the Dockerfile you must to add the following lines just before invoke the apt-get command.

RUN touch /etc/apt/apt.conf.d/30proxy
RUN echo "Acquire::http::proxy \"http://your_user:your_password@proxy_name:proxy_port/\";" > /etc/apt/apt.conf.d/30proxy
RUN echo "Acquire::ftp::proxy \"ftp://your_user:your_password@proxy_name:proxy_port/\";" >> /etc/apt/apt.conf.d/30proxy
RUN echo "Acquire::https::proxy \"https://your_user:your_password@proxy_name:proxy_port/\";" >> /etc/apt/apt.conf.d/30proxy

This works for me and is what I do to build a new docker.

Regards.

**Comment by tianon** [comment] 2017-06-01 20:35
Closing, given that this appears to be network or environment specific and I can't seem to reproduce. :+1:

**Closed by tianon** 2017-06-01 20:35 UTC
