### ISSUE TITLE
docker:dind 20 multi-arch missing for arm/v7

### ISSUE THREAD

**Issue by MaitreDede** [docker-library/docker#286] opened 2021-01-11 00:32 UTC
Hello,

On a Rasperry Pi 4 32bits : `docker pull docker:20.10.2-dind`

```
no matching manifest for linux/arm/v7 in the manifest list entries
```
`docker manifest inspect docker:20.10.2-dind`
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2614,
         "digest": "sha256:12521ff42db0d1e1d99f89c7dea6aa6e2d028c20cb42dad8285503735ddf678d",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2614,
         "digest": "sha256:009bdea1b7cf4de7f5f7febf8cce1f322b92598927318c78cd2c012d8c0dc866",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      }
   ]
}
```

Based on #145 

When I `docker run --rm -it docker:dind docker version` :
```
Client: Docker Engine - Community
 Version:           19.03.8
...
```

**Comment by tianon** [comment] 2021-01-11 02:31
Duplicate of #260

**Closed by tianon** 2021-01-11 02:31 UTC
