### ISSUE TITLE
Add label org.opencontainers.image.source

### ISSUE THREAD

**Issue by marwin1991** [docker-library/docker#395] opened 2023-02-01 07:07 UTC
Hello, for tools like renovate it is important to have define label org.opencontainers.image.source

So can we add label org.opencontainers.image.source="https://github.com/docker-library/docker" to DOCKERFILE ?

Base on this label, renovate will provide information about changes.

https://docs.renovatebot.com/modules/datasource/docker/
https://github.com/opencontainers/image-spec/blob/main/annotations.md

The base idea behind this label is to point to repo with dockerfile, but this repo does not use tag's or releases.
But maybe we can point to some other reposiotry? f.e  https://github.com/moby/moby

What do you think?

**Comment by tianon** [comment] 2023-02-01 18:44
Duplicate of #392

See https://github.com/docker-library/cassandra/issues/260 for a useful (recent) discussion around these annotations.

**Closed by tianon** 2023-02-01 18:44 UTC
