### ISSUE TITLE
buildx is missing from docker:20-dind images

### ISSUE THREAD

**Issue by anapsix** [docker-library/docker#313] opened 2021-06-14 14:05 UTC
**Description**

Docker 20-dind images are shipped with `docker` cli which seems to be missing `buildx` entirely.. which means support for `buildx build --cache-from` is not available.
Launching `docker buildx build --help` on my Macbook shows `--cache-from` available. However launching the same in container instance of `docker:20-dind` does not show `--cache-from` as valid option to `buildx build`.

**Steps to reproduce the issue:**
```sh
$ docker pull docker:20.10.7-dind
$ docker run -it --rm -e DOCKER_CLI_EXPERIMENTAL=enabled docker:20.10.7-dind sh -c 'docker --help | grep buildx && echo SUCCESS: buildx is available || echo ERROR: buildx is not available'
$ docker run -it --rm docker:20.10.7-dind sh -c 'docker --version; docker buildx build --help | grep cache-from || echo "ERROR: buildx build --cache-from is not supported"'
```

**Describe the results you received:**
```
ERROR: buildx is not available
Docker version 20.10.7, build f0df350
ERROR: buildx build --cache-from is not supported
```

**Describe the results you expected:**
```
SUCCESS: buildx is available
Docker version 20.10.7, build f0df350
      --cache-from stringArray   External cache sources (eg. user/app:cache, type=local,src=path/to/dir)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
from `docker:20.10.7-dind` docker image
```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:51:04 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

**Output of `docker info`:**
from `docker:20.10.7-dind` docker image
```
Client:
 Context:    default
 Debug Mode: false

Server:
ERROR: error during connect: Get http://docker:2375/v1.24/info: dial tcp: lookup docker on 192.168.65.5:53: no such host
errors pretty printing info
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Launching `docker run -it --rm docker:20.10.7-dind sh -c ...` on macOS 10.14.6 running `Docker Desktop 3.4.0 (3.4.0.5223)`

**Comment by tianon** [comment] 2021-06-14 17:18
Duplicate of #243, #156

**Closed by tianon** 2021-06-14 17:18 UTC

**Comment by anapsix** [comment] 2021-06-14 17:44
For reference, https://github.com/docker-library/docker/issues/156 includes discussion and clarification on why `buildx` plugin is not included in `docker` images. However, the PR (https://github.com/docker/docker-ce-packaging/pull/415) is open to include base plugins in official docker images.

**Comment by maniator** [comment] 2021-06-28 01:31
I created an image here: `maniator/dind-buildx` exactly for this use :-(
