### ISSUE TITLE
Include buildx cli-plugins

### ISSUE THREAD

**Issue by BarnabyShearer** [docker-library/docker#243] opened 2020-07-13 10:34 UTC
Docker 19.03 includes the `buildx` CLI plugin by default. It would be very helpful if this image could match that.

**Comment by tianon** [comment] 2020-07-13 15:14
Unfortunately, this is a duplicate of #156

**Closed by tianon** 2020-07-13 15:14 UTC
Labels: Request

**Comment by velcrine** [comment] 2021-07-24 08:43
Why the headache to create and maintain a new dockerfile just for one copy command. Can't  docker host it?
