### ISSUE TITLE
Docker does not respect hosts file

### ISSUE THREAD

**Issue by fooker** [docker-library/docker#82] opened 2017-10-05 23:45 UTC
The static docker binary uses the DNS server specified `/etc/resolv.conf` without consulting `/etc/hosts` beforehand. The image should contain a `/etc/nsswitch.conf` containing some minimal configuration which is used by the docker binary.

**Comment by tianon** [comment] 2017-10-05 23:55
I believe this is a duplicate of https://github.com/docker-library/docker/pull/40.

**Comment by fooker** [comment] 2017-10-06 00:14
Not sure. If I add the `nsswitch.conf` with some minimal content like below, it starts working.

```
hosts: files dns
```

**Comment by fooker** [comment] 2017-10-06 00:29
After reading this again, I don't think this is a strict duplicate. Wether or not the native go dns implementation is used or not, in both cases, a `nsswitch.conf` should be provided. The native go implementation also supports a limited version of the file and must be configured to respect `/etc/hosts` (see https://github.com/golang/go/blob/4bd95702dd1e81f383ee67c14945620d30247908/src/net/conf.go#L198).

**Comment by tianon** [comment] 2017-10-11 21:21
Huh, good point -- thinking/looking at it more, I think I like this solution better than that one, since it's adding a general config for DNS lookups rather than a debugging environment variable specifically to try and control Go's behavior (and in a way that's contrary to how upstream intentionally compiled said binary).

Looking a little further down in that same file at https://github.com/golang/go/blob/4bd95702dd1e81f383ee67c14945620d30247908/src/net/conf.go#L219-L253, it appears the only things supported by the `netgo` implementation are `myhostname`, `files`, `dns`, and `mdns*` (and then only `*.local`).

Looking at Debian's default file, it's got `hosts:          files dns`, so I think that's probably what we ought to stick with (perhaps linking to all these resources from a comment).  I'll work up a PR and have something ready to look at/test shortly. :+1:

**Comment by tianon** [comment] 2017-10-11 21:33
https://github.com/docker-library/docker/pull/84 :+1:

**Closed** 2017-10-11 23:55 UTC
