### ISSUE TITLE
Manifest unknown for docker pull docker:*

### ISSUE THREAD

**Issue by max-sternitzke** [docker-library/docker#520] opened 2024-12-14 08:33 UTC
Hey there,

since your recent docker image push today 14th Dec 6:05 UTC i cannot pull any docker image from the official docker registry.
I tried a `docker pull`:
- `docker:27.4.0-dind`
- `docker:27.4.0`
- `docker:latest`
- `docker:dind`

All these result in a `manifest for docker:dind not found: manifest unknown: manifest unknown`

I have not modified my docker/daemon.json. My local Docker version is `Docker version 27.4.0, build bde2b89` on the latest macOS. This problem also occurs on remote Ubuntu VMs.

I'm sorry if its my mistake, but it seems suspicious that the problem occured just after your image push and has not yet been resolved. (We're running a ci pipeline every 5 minutes and it first failed at 6:13am UTC this morning.)
If you need anything, just let me know.

Thanks for any hint or solution. Cheers
Max

**Comment by azlkiniue** [comment] 2024-12-14 09:10
for now i'm downgrading to version 26 temporarily
pulling `docker:26-dind` or `docker:26` is working for me

**Comment by oxilor** [comment] 2024-12-14 10:09
This error started to occur only 4 hours ago since the version `27.4.0` was released. No need to downgrade to `docker:26-dind` because the previous version `docker:27.3.1-dind` is still working.

**Comment by nalingovind** [comment] 2024-12-14 10:11
This worked for me `docker:26-dind`

**Comment by tanc** [comment] 2024-12-14 10:39
`docker:27.3-dind` works fine but latest fails

**Comment by oleksandrmikhnenko** [comment] 2024-12-14 11:40
dind and latest tags are also affected

**Comment by nfacha** [comment] 2024-12-14 12:02
Also experiencing this with the dind tag

**Comment by muocod** [comment] 2024-12-14 12:09
The same shit here

**Comment by thaJeztah** [comment] 2024-12-14 13:30
This looks to be a duplicate of https://github.com/docker-library/docker/issues/519


> 👋 I work at docker, but not on the official images; I'm currently trying our internal slack chatting with folks on call to see if someone working on official images is available to look.
> 
> It looks like the "manifest-index" for the image exists, but the image that's referenced from it is either missing, or resulting in the "not found".
> 
> As a workaround, it looks like the previous versions of the image are functional, so if you pin to the previous version, you can use that as a workaround, e.g.;
> 
> `docker pull docker:27.3.1-dind` / `docker pull docker:27.3.1-cli` both work

**Comment by max-sternitzke** [comment] 2024-12-14 13:47
> This looks to be a duplicate of #519

It sure is @thaJeztah . As i was starting to file the issue the was none, after submitting there were two :)

You better reach someone soon - many pipelines are failing just now because of this.

**Comment by arthurlm44** [comment] 2024-12-14 14:47
The missing tag has completely collapsed our CI system.

**Comment by 0xCiBeR** [comment] 2024-12-14 15:06
Same behavior here, we manged to work arround the issue pointing to this image: ```docker pull public.ecr.aws/docker/library/docker:latest
```

**Comment by thaJeztah** [comment] 2024-12-14 15:31
I can give an intermediate status update from the Slack thread.

Team is still looking. They managed to narrow down the cause of the issue to be related to cross-repo links. The image was pushed successfully (data / blobs are there), but some links were not created after the push, causing it to be producing a 404 for those references. A fix was deployed that should prevent this situation from happening, but won't automatically apply to content that's already there, and those parts are really locked down, so no direct access to (manually) correct, so they're currently checking logs to identify images that are affected (beyond the ones mentioned in this ticket), and to see if there's ways to correct it. Re-pushing the images (same image, but trigger a push again) may work, but may also be locked down (currently being looked into).

**Comment by thaJeztah** [comment] 2024-12-14 16:58
OK, team was able to get the list of images affected, and may have found a solution; some manual work is involved, so fixes may roll out over time. I'll post updates once available.

**Comment by max-sternitzke** [comment] 2024-12-14 17:27
`docker:dind` is working for me again. Thanks for the work @thaJeztah & team! 🎉 

Nevertheless I have to disagree with @marcschroeder quite a bit. After the weekend the Docker team will recap that for sure and pull the necessary clues so such a situation will most likely not happen again.

**Comment by MrCskncn** [comment] 2024-12-14 17:49
"the one should not release a version on friday evenings."

**Comment by thaJeztah** [comment] 2024-12-14 19:07
x-posting from the other ticket;

> I think they managed to go through most of the list by now, but some may still be pending. Currently verifying all tags and all variants of those images (which takes a while to run).
> 
> There may be some images in the platform-specific orgs that are used as intermediate image that may not yet be addressed, and (given much lower / corner-case use), e.g. images in the platrform-specific namespace (e.g. https://hub.docker.com/u/arm64v8/, and other similar namespaces listed in; https://github.com/docker-library/official-images#architectures-other-than-amd64. Those namespaces are effectively intermediate stages for the multi-platform images.

> OK; colleague confirmed that the list of official images should be all processed. The verification script will still be running for some hours, but we're updating the statuspage to "monitoring"
> 
> > There may be some images in the platform-specific orgs that are used as intermediate image that may not yet be addressed, and (given much lower / corner-case use), e.g. images in the platrform-specific namespace (e.g. https://hub.docker.com/u/arm64v8/, and other similar namespaces listed in; https://github.com/docker-library/official-images#architectures-other-than-amd64. Those namespaces are effectively intermediate stages for the multi-platform images.
> 
> These images will likely be processed later, which may be done after the weekend.

**Comment by LaurentGoderre** [comment] 2024-12-14 22:53
Closing in favor of #519. It should be mostly resolve now though

**Closed by LaurentGoderre** 2024-12-14 22:53 UTC
