### ISSUE TITLE
docker:19.03.1-dind image in Gitlab CI yields a boatload of errors

### ISSUE THREAD

**Issue by interone-ms** [docker-library/docker#214] opened 2020-01-22 16:30 UTC
Hi,

I'm having an issue with the docker:dind image in conjunction with gitlab-runner for months now. The docker:dind service container (according to Gitlab!) doesn't start properly and junks the logs, but running docker commands actually works.

I have disabled TLS by setting `DOCKER_TLS_CERTDIR: ""`, so that is not the issue.

Additionally, despite the modules being already present in the kernel, the dind image tries to load them anyway and annoys the user with strange warnings.

I have attached the relevant logs both of gitlab and lsmod. The issue is distinct from the already fixed #170 as running docker commands does work, it is purely about the issue with the erroneous healthcheck error.

```
Running with gitlab-runner 12.7.0 (58272c27)
  on xxx 55304814
Using Docker executor with image docker:19.03.1 ...
Starting service docker:19.03.1-dind ...
Pulling docker image docker:19.03.1-dind ...
Using docker image sha256:f20e73ae0611ce447dbbd26d8b62eb87a966a7e5b54c32d071d601e411d78d9d for docker:19.03.1-dind ...
Waiting for services to be up and running...

*** WARNING: Service runner-55304814-project-756-concurrent-1-docker-0 probably didn't start properly.

Health check error:
service "runner-55304814-project-756-concurrent-1-docker-0-wait-for-service" timeout

Health check container logs:


Service container logs:
2020-01-22T16:10:00.984047770Z time="2020-01-22T16:10:00.983902729Z" level=info msg="Starting up"
2020-01-22T16:10:00.985361097Z time="2020-01-22T16:10:00.985286635Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
2020-01-22T16:10:00.985597671Z time="2020-01-22T16:10:00.985501106Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
2020-01-22T16:10:00.986974911Z time="2020-01-22T16:10:00.986845651Z" level=info msg="libcontainerd: started new containerd process" pid=23
2020-01-22T16:10:00.987001771Z time="2020-01-22T16:10:00.986900723Z" level=info msg="parsed scheme: \"unix\"" module=grpc
2020-01-22T16:10:00.987020512Z time="2020-01-22T16:10:00.986920826Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
2020-01-22T16:10:00.987036947Z time="2020-01-22T16:10:00.986953946Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] }" module=grpc
2020-01-22T16:10:00.987046067Z time="2020-01-22T16:10:00.986979526Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
2020-01-22T16:10:00.987254187Z time="2020-01-22T16:10:00.987083841Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0007feb60, CONNECTING" module=grpc
2020-01-22T16:10:01.005111294Z time="2020-01-22T16:10:01.004986837Z" level=info msg="starting containerd" revision=894b81a4b802e4eb2a91d1ce216b8817763c29fb version=v1.2.6 
2020-01-22T16:10:01.005663069Z time="2020-01-22T16:10:01.005601983Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." type=io.containerd.content.v1 
2020-01-22T16:10:01.005792369Z time="2020-01-22T16:10:01.005714255Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." type=io.containerd.snapshotter.v1 
2020-01-22T16:10:01.006046155Z time="2020-01-22T16:10:01.005978541Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" 
2020-01-22T16:10:01.006064677Z time="2020-01-22T16:10:01.006001828Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.aufs"..." type=io.containerd.snapshotter.v1 
2020-01-22T16:10:01.014571145Z time="2020-01-22T16:10:01.014382757Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.aufs" error="modprobe aufs failed: "ip: can't find device 'aufs'\naufs                  274432  0 \nmodprobe: can't change directory to '/lib/modules': No such file or directory\n": exit status 1" 
2020-01-22T16:10:01.014599371Z time="2020-01-22T16:10:01.014419965Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.native"..." type=io.containerd.snapshotter.v1 
2020-01-22T16:10:01.014614329Z time="2020-01-22T16:10:01.014563156Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." type=io.containerd.snapshotter.v1 
2020-01-22T16:10:01.014878562Z time="2020-01-22T16:10:01.014767819Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1 
2020-01-22T16:10:01.015146587Z time="2020-01-22T16:10:01.015041327Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.zfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter" 
2020-01-22T16:10:01.015177450Z time="2020-01-22T16:10:01.015060685Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1 
2020-01-22T16:10:01.015191800Z time="2020-01-22T16:10:01.015125881Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" 
2020-01-22T16:10:01.015199869Z time="2020-01-22T16:10:01.015145300Z" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "ip: can't find device 'aufs'\naufs                  274432  0 \nmodprobe: can't change directory to '/lib/modules': No such file or directory\n": exit status 1" 
2020-01-22T16:10:01.015212939Z time="2020-01-22T16:10:01.015162016Z" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter" 
2020-01-22T16:10:01.134806804Z time="2020-01-22T16:10:01.134667574Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1 
2020-01-22T16:10:01.134854849Z time="2020-01-22T16:10:01.134720765Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1 
2020-01-22T16:10:01.134913431Z time="2020-01-22T16:10:01.134787175Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1 
2020-01-22T16:10:01.134934644Z time="2020-01-22T16:10:01.134823937Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1 
2020-01-22T16:10:01.134948089Z time="2020-01-22T16:10:01.134848213Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1 
2020-01-22T16:10:01.134960307Z time="2020-01-22T16:10:01.134875074Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1 
2020-01-22T16:10:01.134987728Z time="2020-01-22T16:10:01.134894799Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1 
2020-01-22T16:10:01.135006864Z time="2020-01-22T16:10:01.134918883Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1 
2020-01-22T16:10:01.135018705Z time="2020-01-22T16:10:01.134937737Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1 
2020-01-22T16:10:01.135032168Z time="2020-01-22T16:10:01.134969615Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1 
2020-01-22T16:10:01.135322476Z time="2020-01-22T16:10:01.135262169Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2 
2020-01-22T16:10:01.135490147Z time="2020-01-22T16:10:01.135427309Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1 
2020-01-22T16:10:01.136357908Z time="2020-01-22T16:10:01.136275928Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1 
2020-01-22T16:10:01.136379017Z time="2020-01-22T16:10:01.136315370Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1 
2020-01-22T16:10:01.136453872Z time="2020-01-22T16:10:01.136383039Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1 
2020-01-22T16:10:01.136477152Z time="2020-01-22T16:10:01.136417176Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1 
2020-01-22T16:10:01.136490892Z time="2020-01-22T16:10:01.136449534Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1 
2020-01-22T16:10:01.136527878Z time="2020-01-22T16:10:01.136476758Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1 
2020-01-22T16:10:01.136546929Z time="2020-01-22T16:10:01.136505724Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1 
2020-01-22T16:10:01.136577296Z time="2020-01-22T16:10:01.136534328Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1 
2020-01-22T16:10:01.136601141Z time="2020-01-22T16:10:01.136559599Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1 
2020-01-22T16:10:01.136615939Z time="2020-01-22T16:10:01.136582620Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1 
2020-01-22T16:10:01.136629931Z time="2020-01-22T16:10:01.136600767Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1 
2020-01-22T16:10:01.137051290Z time="2020-01-22T16:10:01.136988827Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1 
2020-01-22T16:10:01.137070889Z time="2020-01-22T16:10:01.137020032Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1 
2020-01-22T16:10:01.137085615Z time="2020-01-22T16:10:01.137040374Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1 
2020-01-22T16:10:01.137101289Z time="2020-01-22T16:10:01.137066654Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1 
2020-01-22T16:10:01.137445896Z time="2020-01-22T16:10:01.137391833Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock" 
2020-01-22T16:10:01.137566634Z time="2020-01-22T16:10:01.137506543Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock" 
2020-01-22T16:10:01.137588705Z time="2020-01-22T16:10:01.137534076Z" level=info msg="containerd successfully booted in 0.133256s" 
2020-01-22T16:10:01.145257807Z time="2020-01-22T16:10:01.145103427Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0007feb60, READY" module=grpc
2020-01-22T16:10:01.147766345Z time="2020-01-22T16:10:01.147615122Z" level=info msg="Setting the storage driver from the $DOCKER_DRIVER environment variable (overlay2)"
2020-01-22T16:10:01.148087932Z time="2020-01-22T16:10:01.148026523Z" level=info msg="parsed scheme: \"unix\"" module=grpc
2020-01-22T16:10:01.148101317Z time="2020-01-22T16:10:01.148052842Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
2020-01-22T16:10:01.148155657Z time="2020-01-22T16:10:01.148089541Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] }" module=grpc
2020-01-22T16:10:01.148167891Z time="2020-01-22T16:10:01.148116282Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
2020-01-22T16:10:01.148291131Z time="2020-01-22T16:10:01.148211292Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00014b390, CONNECTING" module=grpc
2020-01-22T16:10:01.148319972Z time="2020-01-22T16:10:01.148230036Z" level=info msg="blockingPicker: the picked transport is not ready, loop back to repick" module=grpc
2020-01-22T16:10:01.148701331Z time="2020-01-22T16:10:01.148591852Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00014b390, READY" module=grpc
2020-01-22T16:10:01.149560850Z time="2020-01-22T16:10:01.149432702Z" level=info msg="parsed scheme: \"unix\"" module=grpc
2020-01-22T16:10:01.149584986Z time="2020-01-22T16:10:01.149464974Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
2020-01-22T16:10:01.149593487Z time="2020-01-22T16:10:01.149498049Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] }" module=grpc
2020-01-22T16:10:01.149600757Z time="2020-01-22T16:10:01.149524769Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
2020-01-22T16:10:01.149682111Z time="2020-01-22T16:10:01.149608213Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00014b8c0, CONNECTING" module=grpc
2020-01-22T16:10:01.156866733Z time="2020-01-22T16:10:01.153394913Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00014b8c0, READY" module=grpc
2020-01-22T16:10:01.355833263Z time="2020-01-22T16:10:01.355707275Z" level=warning msg="Your kernel does not support swap memory limit"
2020-01-22T16:10:01.355869129Z time="2020-01-22T16:10:01.355741206Z" level=warning msg="Your kernel does not support cgroup rt period"
2020-01-22T16:10:01.355882429Z time="2020-01-22T16:10:01.355751566Z" level=warning msg="Your kernel does not support cgroup rt runtime"
2020-01-22T16:10:01.356594739Z time="2020-01-22T16:10:01.355996972Z" level=info msg="Loading containers: start."
2020-01-22T16:10:01.409604295Z time="2020-01-22T16:10:01.409419624Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: ip: can't find device 'bridge'\nbridge                188416  1 br_netfilter\nstp                    16384  2 garp,bridge\nllc                    16384  3 garp,bridge,stp\nip: can't find device 'br_netfilter'\nbr_netfilter           24576  0 \nbridge                188416  1 br_netfilter\nmodprobe: can't change directory to '/lib/modules': No such file or directory\n, error: exit status 1"
2020-01-22T16:10:01.430331576Z time="2020-01-22T16:10:01.430166151Z" level=warning msg="Running modprobe nf_nat failed with message: `ip: can't find device 'nf_nat'\nnf_nat_ipv4            16384  3 iptable_nat,ipt_MASQUERADE,nft_chain_nat_ipv4\nnf_nat                 36864  3 xt_REDIRECT,xt_nat,nf_nat_ipv4\nnf_conntrack          172032  8 xt_REDIRECT,xt_connmark,xt_nat,xt_conntrack,ipt_MASQUERADE,nf_conntrack_netlink,nf_nat_ipv4,nf_nat\nlibcrc32c              16384  5 xfs,nf_nat,nf_conntrack,btrfs,raid456\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
2020-01-22T16:10:01.438255722Z time="2020-01-22T16:10:01.438107693Z" level=warning msg="Running modprobe xt_conntrack failed with message: `ip: can't find device 'xt_conntrack'\nxt_conntrack           16384  6 \nnf_conntrack          172032  8 xt_REDIRECT,xt_connmark,xt_nat,xt_conntrack,ipt_MASQUERADE,nf_conntrack_netlink,nf_nat_ipv4,nf_nat\nx_tables               45056 13 iptable_filter,xt_REDIRECT,xt_mark,xt_connmark,xt_comment,xt_CHECKSUM,xt_nat,xt_tcpudp,xt_conntrack,ipt_MASQUERADE,xt_addrtype,nft_compat,ip_tables\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
2020-01-22T16:10:01.707479411Z time="2020-01-22T16:10:01.707335568Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address"
2020-01-22T16:10:01.799145937Z time="2020-01-22T16:10:01.798571997Z" level=info msg="Loading containers: done."
2020-01-22T16:10:01.875282716Z time="2020-01-22T16:10:01.875156265Z" level=info msg="Docker daemon" commit=74b1e89e8a graphdriver(s)=overlay2 version=19.03.1
2020-01-22T16:10:01.875385472Z time="2020-01-22T16:10:01.875336911Z" level=info msg="Daemon has completed initialization"
2020-01-22T16:10:01.983176427Z time="2020-01-22T16:10:01.982953144Z" level=info msg="API listen on /var/run/docker.sock"
2020-01-22T16:10:01.983213425Z time="2020-01-22T16:10:01.982954098Z" level=info msg="API listen on [::]:2375"

*********
```

lsmod:
```
$ lsmod
Module                  Size  Used by
vhost_net              24576  1
vhost                  49152  1 vhost_net
tap                    28672  1 vhost_net
tun                    49152  3 vhost_net
iptable_nat            16384  0
iptable_filter         16384  0
xt_REDIRECT            16384  1
nft_chain_route_ipv6    16384  1
xt_mark                16384  7
xt_connmark            16384  8
xt_comment             16384  0
nft_chain_route_ipv4    16384  3
xt_CHECKSUM            16384  3
vxlan                  57344  0
ip6_udp_tunnel         16384  1 vxlan
udp_tunnel             16384  1 vxlan
devlink                77824  0
xfs                  1458176  1
loop                   36864  2
nfsv3                  53248  1
nfs_acl                16384  1 nfsv3
rpcsec_gss_krb5        45056  0
auth_rpcgss            73728  1 rpcsec_gss_krb5
nfsv4                 684032  0
dns_resolver           16384  1 nfsv4
nfs                   311296  5 nfsv4,nfsv3
lockd                 118784  2 nfsv3,nfs
grace                  16384  1 lockd
fscache               385024  2 nfsv4,nfs
xt_nat                 16384  16
xt_tcpudp              16384  48
veth                   20480  0
8021q                  40960  0
garp                   16384  1 8021q
mrp                    20480  1 8021q
bonding               180224  0
xt_conntrack           16384  5
ipt_MASQUERADE         16384  17
nf_conntrack_netlink    49152  0
xfrm_user              40960  1
xfrm_algo              16384  1 xfrm_user
nft_counter            16384  169
xt_addrtype            16384  2
nft_compat             20480  107
nft_chain_nat_ipv4     16384  16
nf_nat_ipv4            16384  3 ipt_MASQUERADE,nft_chain_nat_ipv4,iptable_nat
nf_nat                 36864  3 nf_nat_ipv4,xt_nat,xt_REDIRECT
nf_conntrack          172032  8 xt_conntrack,nf_nat,ipt_MASQUERADE,nf_nat_ipv4,xt_nat,nf_conntrack_netlink,xt_connmark,xt_REDIRECT
nf_defrag_ipv6         20480  1 nf_conntrack
nf_defrag_ipv4         16384  1 nf_conntrack
nf_tables             143360  574 nft_chain_route_ipv4,nft_compat,nft_chain_nat_ipv4,nft_counter,nft_chain_route_ipv6
nfnetlink              16384  4 nft_compat,nf_conntrack_netlink,nf_tables
aufs                  274432  0
ipmi_ssif              32768  0
overlay               131072  12
intel_powerclamp       16384  0
coretemp               16384  0
kvm_intel             233472  6
ttm                   131072  0
kvm                   729088  1 kvm_intel
drm_kms_helper        208896  0
irqbypass              16384  4 kvm
drm                   495616  2 drm_kms_helper,ttm
intel_cstate           16384  0
ipmi_si                65536  0
iTCO_wdt               16384  0
serio_raw              16384  0
pcspkr                 16384  0
i2c_algo_bit           16384  0
ipmi_devintf           20480  0
evdev                  28672  3
intel_uncore          135168  0
pcc_cpufreq            16384  0
i7core_edac            28672  0
iTCO_vendor_support    16384  1 iTCO_wdt
hpilo                  20480  0
hpwdt                  16384  0
sg                     36864  0
ipmi_msghandler        65536  3 ipmi_devintf,ipmi_si,ipmi_ssif
button                 16384  0
acpi_power_meter       20480  0
ib_iser                57344  0
rdma_cm                69632  1 ib_iser
iw_cm                  49152  1 rdma_cm
ib_cm                  57344  1 rdma_cm
ib_core               274432  4 rdma_cm,iw_cm,ib_iser,ib_cm
configfs               45056  2 rdma_cm
iscsi_tcp              20480  0
libiscsi_tcp           24576  1 iscsi_tcp
libiscsi               61440  3 libiscsi_tcp,iscsi_tcp,ib_iser
scsi_transport_iscsi   110592  3 iscsi_tcp,ib_iser,libiscsi
br_netfilter           24576  0
bridge                188416  1 br_netfilter
stp                    16384  2 bridge,garp
llc                    16384  3 bridge,stp,garp
sunrpc                425984  25 nfsv4,auth_rpcgss,lockd,nfsv3,rpcsec_gss_krb5,nfs_acl,nfs
ip_tables              28672  2 iptable_filter,iptable_nat
x_tables               45056  13 xt_conntrack,iptable_filter,nft_compat,xt_tcpudp,ipt_MASQUERADE,xt_addrtype,xt_CHECKSUM,xt_nat,xt_comment,xt_connmark,ip_tables,xt_REDIRECT,xt_mark
autofs4                49152  2
ext4                  737280  1
crc16                  16384  1 ext4
mbcache                16384  1 ext4
jbd2                  122880  1 ext4
fscrypto               32768  1 ext4
ecb                    16384  0
crypto_simd            16384  0
cryptd                 28672  1 crypto_simd
glue_helper            16384  0
aes_x86_64             20480  1
btrfs                1400832  0
zstd_decompress        81920  1 btrfs
zstd_compress         172032  1 btrfs
xxhash                 16384  2 zstd_compress,zstd_decompress
raid10                 57344  0
raid456               172032  0
async_raid6_recov      20480  1 raid456
async_memcpy           16384  2 raid456,async_raid6_recov
async_pq               16384  2 raid456,async_raid6_recov
async_xor              16384  3 async_pq,raid456,async_raid6_recov
async_tx               16384  5 async_pq,async_memcpy,async_xor,raid456,async_raid6_recov
xor                    24576  2 async_xor,btrfs
raid6_pq              122880  4 async_pq,btrfs,raid456,async_raid6_recov
libcrc32c              16384  5 nf_conntrack,nf_nat,btrfs,xfs,raid456
crc32c_generic         16384  0
raid1                  45056  0
raid0                  20480  0
multipath              16384  0
linear                 16384  0
md_mod                167936  6 raid1,raid10,raid0,linear,raid456,multipath
hid_generic            16384  0
usbhid                 57344  0
hid                   135168  2 usbhid,hid_generic
sr_mod                 28672  0
cdrom                  65536  1 sr_mod
ata_generic            16384  0
sd_mod                 61440  3
uhci_hcd               49152  0
ehci_pci               16384  0
ehci_hcd               94208  1 ehci_pci
ata_piix               36864  0
hpsa                  106496  2
libata                270336  2 ata_piix,ata_generic
scsi_transport_sas     45056  1 hpsa
usbcore               294912  4 ehci_pci,usbhid,ehci_hcd,uhci_hcd
psmouse               172032  0
lpc_ich                28672  0
crc32c_intel           24576  3
usb_common             16384  1 usbcore
bnx2                   94208  0
scsi_mod              249856  10 scsi_transport_sas,sd_mod,scsi_transport_iscsi,iscsi_tcp,hpsa,ib_iser,libiscsi,libata,sg,sr_mod
e1000e                282624  0
thermal                20480  0
```

**Comment by wglambert** [comment] 2020-01-22 17:40
Are you using a user-defined network https://gitlab.com/gitlab-org/gitlab-runner/issues/1592

This seems more like an issue with gitlab runners. If the container starts up fine but their healthcheck is failing then I don't know what we could change in the image to alleviate that. 
I'd suggest making an issue on their repo for this

**Comment by interone-ms** [comment] 2020-01-23 10:52
Apparently it is a combined issue - turns out that when one sets `DOCKER_TLS_CERTDIR` to empty, then Docker doesn't listen on TCP 2376 any more but on TCP 2375 instead. Kinda makes sense, but there is no way for the GitLab healthcheck to know where Docker is listening.

Is there a way to have Docker listen on *both* 2375 and 2376 if TLS is enabled? This way the Gitlab healthcheck can always check TCP 2375 to see if Docker is alive.

For those coming in via google, specify this in `.gitlab-ci.yml`:

```
variables:
  SERVICE_PORT_2376_TCP_PORT: 2375
```
(per https://gitlab.com/gitlab-org/gitlab-runner/issues/4635#note_204682505)

**Comment by tianon** [comment] 2020-01-24 00:55
Ah yes, there was some discussion around that over in https://github.com/docker-library/docker/pull/173 where we were trying to help come up with a solution to their healthcheck woes more generically.

If you just want both ports, you can easily specify `--host tcp://0.0.0.0:2376` to the entrypoint script (or better yet, if you're looking to skip TLS anyhow, just skip the entrypoint entirely and do an explicit `--entrypoint dockerd docker:dind --host tcp://0.0.0.0:2375 --host tcp://0.0.0.0:2376`), but IMO it's still cleaner to inform GitLab which port the service is going to be listening on (or for them to enhance their healthcheck to account for two entries in `EXPOSE` more dynamically).

**Comment by tmaczukin** [comment] 2020-02-14 14:00
Yes, in this specific case the problem is rather in our healthcheck mechanism. Image update around the `19.03` release caused some problems, but they were resolved on both `docker:dind` image and GitLab's documentation side. The last thing left is that nasty healthcheck message that doesn't work well when ports are not reported as Runner expects it.

I suggest to close this issue, because there is nothing much to do here. Instead please follow https://gitlab.com/gitlab-org/gitlab-runner/issues/3984 to be up-to-date with when we'll update the helathcheck in GitLab Runner :)

**Closed** 2020-02-14 22:40 UTC
Labels: question
