### ISSUE TITLE
docker:dind version inconsistency

### ISSUE THREAD

**Issue by rkojedzinszky** [docker-library/docker#289] opened 2021-01-27 22:07 UTC
Latest docker:dind image contains docker version 20 for amd64, and version 19 for armhf.

**Comment by tianon** [comment] 2021-01-27 22:13
Yep, unfortunately see https://github.com/docker-library/docker/issues/260 (which I'd consider this a duplicate of, although the title there isn't completely accurate since 20.x suffers from the same issue, as you've noticed)

**Closed** 2021-08-20 23:28 UTC
